In [5]:
import pandas as pd 
fooddf = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv' ,encoding = 'latin-1')

FileNotFoundError: ignored

In [ ]:
fooddf.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [1]:
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [6]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: ignored

In [ ]:
fooddf.groupby("Element")[['Y2014','Y2015','Y2016',	'Y2017','Y2018']].sum()

,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,
Domestic supply quantity,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),10225.56,10235.74,10102.77,10253.84,10258.69
Feed,216927.89,225050.22,228958.65,223705.68,233489.68
Food,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),78718.13,66254.41,69563.68,91645.97,91300.97
Processing,282923.00,287929.00,280631.00,292836.00,308429.00
Production,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,416.00,349.00,89.00,91.00,90.00

In [4]:
fooddf.groupby("Area")[	'Y2017'].sum().sort_values()

NameError: ignored

TypeError: ignored